### PR TITLE
Add ability to decelerate in normal mode

### PR DESCRIPTION
**Pull request by ChrispyChris**
I've been continuing to use and absolutely love this tool, and I find myself struggling sometimes to make minor adjustments in normal mode. Even if I tap the key, it still moves too fast. This is an attempt to add more fine-grained control with a deceleration key.

I'm not sure if you want to allow something like this in or not, but I wanted to at least make a pull request to see what you thought.

Also, I have been struggling to really make the cursor move any slower no matter what I adjust at this point. The deceleration does work, but not to the extent that I'd like. 

If this is something you're interested in adding in, maybe you could take a look at that last part?

Thank you!

### CODE REVIEW

**Comment by rvaiya** [comment]
Thanks for the patch, however I generally try and take a conservative approach to features (hard though it may be to believe). If you feel something should be included you should make a case for it in a dedicated issue.

> I tap the key, it still moves too fast.

This shouldn't be an problem. Have you tried tuning both `speed` and `acceleration`?  As they approach 0, you shouldn't be able to detect any visible cursor movement.

> I'm not sure if you want to allow something like this in or not

I am not necessarily opposed to this if a good case for it can be made, however I am inclined to encourage the user to set a sane base speed and then use the accelerator key if/when necessary given that there are already dedicated modes for larger movements.

**Comment by ChrispyChris** [comment]
Ahh no problem, I completely understand. My bad on not opening an issue first. Still figuring out GitHub and all :).

Well I did tune those and then it began working, however I'm having an issue and after digging around for a decent amount of time, I cannot figure out exactly what's going on. When I press the key to decelerate, it works but if I change direction then I lose the deceleration. I believe that's what is happening. I was trying to figure it out but have given up for tonight as it's getting late. 

I don't know if this is a feature that you're interested in or not, but if you don't feel like digging into this anymore, you can feel free to close this. I think after giving it the shot I did, I'm stuck and don't care enough myself to keep at it haha. The amount of times I need to be that accurate aren't huge, and I'm not advanced in C enough to do this in a timely manner I don't think :P.

Thank you either way for the response. If I think of anything else in the future, I'll be sure to open an issue!

**Comment by rvaiya** [comment]
> Also, I have been struggling to really make the cursor move any slower no matter what I adjust at this point. The deceleration does work, but not to the extent that I'd like.

This is probably because you've set `d0` to a positive value. If you want the cursor to actually slow down (from its base speed) you need to make this a value negative. You will likely also want to introduce some kind of floor.

> Ahh no problem, I completely understand. My bad on not opening an issue first.  Still figuring out GitHub and all :).

No worries.

> Well I did tune those and then it began working, however I'm having an issue
and after digging around for a decent amount of time, I cannot figure out
When I press the key to decelerate, it works but if I change direction then I lose the deceleration.

You likely need to update the resting logic in `tick()`. At present it will reset the pointer speed if the pointer reaches a neutral state (i.e left and right are simultaneously held).

> I don't know if this is a feature that you're interested in or not, but if you don't feel like digging into this anymore, you can feel free to close this.

There is nothing inherently wrong with the feature, but my main concern is that encourages bad usage patterns. The user should set the cursor speed should be low enough to facilitate pixel-precise movements and use `a` and `x` for larger movements.

The patch itself looks mostly ok, but you have committed the mortal sin of mixing tabs and spaces ;). Most C projects tend to favour tabs of size 8, with spaces used for indentation. When it doubt immitate the code you see.

**Comment by ChrispyChris** [comment]
Ahh, after reading this last message from you and adjusting my speed and accelerations, I do prefer it this way. I apologize for the mistake, and I'll close this now as I feel comfortable with your suggestion :)!

As usual, thanks a ton for this program. Still loving it!

**Pull request closed without merging**
