### PR TITLE
Add option to configure hint font

### PR DESCRIPTION
**Pull request by meain**
I don't write a lot of `C`, so let me know if there is anything that looks odd.

Reference for fix in `open`: https://github.com/facebook/hhvm/commit/f55604ba3d916ab39354af67852583ec79038710

### CODE REVIEW

**Comment by rvaiya** [comment]
The open() fix looks fine, but I'm not sure about exposing the font family since this isn't consistently represented across platforms. It's not obvious what the font names correspond to (xft patterns, postscript names, etc). 

Additionally, I believe I make some assumptions about monospace fonts in the width calculations. It might be possible to make this more platform agnostic with some effort, but I'm not sure it's worth it given than hints are only briefly displayed. 

I am also not opposed to changing the default value if you find the current one objectionable for some reason. Do you feel a pressing need for this?

**Comment by meain** [comment]
I can send the `open` change separately. I would like to have that so that I can build it under [nix](https://nixos.org/).

As for the fonts, I personally prefer to have all programs use the same fonts, but it is not that big a deal. If the platform specific parts is just the naming, then that is technically the "user's problem" to figure out what the name is as this is an *extra* customization option. About calculating width, I'm assuming that it will be fine as long as we use another monospace font(just allowing monospace open up a lot of options). We can maybe have this as a disclaimer that proportional fonts might not work?

With all that said, I understand if you don't wanna include it as it might feel half baked.

**Comment by rvaiya** [comment]
> I can send the open change separately. I would like to have that so that I can build it under nix.

No need, I have merged the relevant commit (thanks for splitting the PR up nicely).

> As for the fonts, I personally prefer to have all programs use the same fonts, but it is not that big a deal.

Fair enough :P.

> If the platform specific parts is just the naming, then that is technically the "user's problem" to figure out what the name is as this is an extra customization option. About calculating width, I'm assuming that it will be fine as long as we use another monospace font(just allowing monospace open up a lot of options). We can maybe have this as a disclaimer that proportional fonts might not work?

Let me think about this a bit more.

**Comment by rvaiya** [comment]
Custom fonts are supported in the latest release. I am closing this for now.

**Pull request closed without merging**
